# @file
##
# Configuration for building authenticated variables
##
# Copyright (C) Microsoft Corporation
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
############################
# Default PK File Entry    #
############################
[DefaultPk]
# help = "Contains the Microsoft PK to enable signature database updates and binary execution."
help = "Contains the OEMA0 PK to enable signature database updates and binary execution."

# [[DefaultPk.files]]
# path = "keystore/Pk/WindowsOEMDevicesPK.der"
# sha1 = 0x3D8660C0CB2D57B189C3D7995572A552F75E48B5

[[DefaultPk.files]]
path = "keystore/OEMA0-PK.der"
sha1 = 0xC68AA0FB846E5A08439DDD5FD3BADFE4BB84D97C

############################
# Default Kek File Entries #
############################
[DefaultKek]
# help = "Contains the Microsoft KEKs to enable signature database updates and binary execution."
help = "Contains the Microsoft KEKs and OEMA0 KEK to enable signature database updates and binary execution."

[[DefaultKek.files]]
path = "keystore/Kek/MicCorKEKCA2011_2011-06-24.der"
url = "https://go.microsoft.com/fwlink/?LinkId=321185"
sha1 = 0x31590bfd89c9d74ed087dfac66334b3931254b30

[[DefaultKek.files]]
path = "keystore/Kek/microsoft_corporation_kek_2k_ca_2023.der"
url = "https://go.microsoft.com/fwlink/?linkid=2239775"
sha1 = 0x459ab6fb5e284d272d5e3e6abc8ed663829d632b

[[DefaultKek.files]]
path = "keystore/OEMA0-KEK.der"
url = "https://github.com/WOA-Project/SurfaceDuoPkg"
sha1 = 0xd9254dac570e3d582b429b162a70e7ad23fc5736

###########################
# Default Db File Entries #
###########################
[DefaultDb]
help = "Contains only Microsoft certificates to verify binaries before execution. More secure than Default3PDb."

[[DefaultDb.files]]
path = "keystore/Db/MicWinProPCA2011_2011-10-19.der"
url = "https://go.microsoft.com/fwlink/p/?linkid=321192"
sha1 = 0x580a6f4cc4e4b669b9ebdc1b2b3e087b80d0678d

[[DefaultDb.files]]
path = "keystore/Db/windows_uefi_ca_2023.der"
url = "https://go.microsoft.com/fwlink/?linkid=2239776"
sha1 = 0x45a0fa32604773c82433c3b7d59e7466b3ac0c67

#####################################
# Default 3rd Party Db File Entries #
#####################################
[Default3PDb]
help = "Contains Microsoft and UEFI third party certificates to verify binaries before execution. More compatible than DefaultDb."

[[Default3PDb.files]]
path = "keystore/Db/MicWinProPCA2011_2011-10-19.der"
url = "https://go.microsoft.com/fwlink/p/?linkid=321192"
sha1 = 0x580a6f4cc4e4b669b9ebdc1b2b3e087b80d0678d

[[Default3PDb.files]]
path = "keystore/Db/windows_uefi_ca_2023.der"
url = "https://go.microsoft.com/fwlink/?linkid=2239776"
sha1 = 0x45a0fa32604773c82433c3b7d59e7466b3ac0c67

[[Default3PDb.files]]
path = "keystore/Db/MicCorUEFCA2011_2011-06-27.der"
url = "https://go.microsoft.com/fwlink/p/?linkid=321194"
sha1 = 0x46def63b5ce61cf8ba0de2e6639c1019d0ed14f3

[[Default3PDb.files]]
path = "keystore/Db/microsoft_uefi_ca_2023.der"
url = "https://go.microsoft.com/fwlink/?linkid=2239872"
sha1 = 0xb5eeb4a6706048073f0ed296e7f580a790b59eaa

############################
# Default Dbx File Entries #
############################
[DefaultDbx]
help = "Contains a list of revoked certificates that will not execute on this system. Filtered per Architecture (ARM, Intel)."

[[DefaultDbx.files]]
path = "keystore/Dbx/dbx_info_uefi_org_7_18_23.csv"
url = "https://uefi.org/sites/default/files/resources/dbx_info.csv"
sha1 = 0x501379f1564a6bfc08e1e584767501bae9fd8907
